exports.TOGGLE_SEARCH_INPUT = 'HS_TOGGLE_SEARCH_INPUT';
exports.TOGGLE_CASE_INSENSITIVE_ACTION = "HS_TOGGLE_CASE_INSENSITIVE_ACTION";
exports.UPDATE_SEARCH_TEXT = 'HS_UPDATE_SEARCH_TEXT';
exports.CURRENT_MATCH = 'HS_CURRENT_MATCH';
